### PR TITLE
fix: [Inspector] drop Proxies, set selective Object.defineProperties traps

### LINKED ISSUE #429: Inspector RTT support is broken
Inspector seems to break when RTT nodes are enabled, it even stalls the rendering itself.

Without inspector:
image (2)

With inspector enabled:
image (3)

With inspector enabled and RTT disabled:
image (4)

### PR DESCRIPTION
**Pull request by wouterlucas**
Proxies introduce a delay and differences in update graph behaviour which break the RTT parent/child updates on nodes itself, to avoid the issue only enable traps for inspector elements that we're actually interested in.

Fixes #429

### CODE REVIEW

File: src/main-api/Inspector.ts [hunk 1]
```diff
@@ -239,72 +247,87 @@ export class Inspector {
...
-      },
-      get: (target, property: keyof CoreNode, receiver: any): any => {
-        if (property === 'destroy') {
-          this.destroyNode(target.id);
-        }
+    const updateNodePropertyWrapper = (
+      property: keyof CoreNodeProps,
+      value: any,
+    ) => {
+      queueMicrotask(() => this.updateNodeProperty(div, property, value));
```
Comment (elsassph) [inline src/main-api/Inspector.ts:277]: Is the delay useful?

Comment (wouterlucas) [reply src/main-api/Inspector.ts:277]: The issue wasn't on the performance of the DOM nodes but the impact Proxies and the inspector updates had on the CoreNode processing itself.

Though I don't mind taking it out if we see risk/concern on the DOM side, can always add it back if we need it.

Comment (elsassph) [reply src/main-api/Inspector.ts]: JS is synchronous so you will only slow down things a bit.

**Review by michielvandergeest — APPROVED** [review]
LGTM
